### ISSUE TITLE
缺少文件夹server/public

### ISSUE THREAD

**Issue by changqing91** [tnfe/shida#1]
[FF] Creator production error. "ENOENT: no such file or directory, lstat '/Users/green/Git/shida/server/public/static/demo'"
[FF] Creator production error. "ENOENT: no such file or directory, lstat '/Users/green/Git/shida/server/public/static/demo/wryh.ttf'"

**Comment by aliaszz** [comment]
对publish进行了优化，可以重新pull一下。
