### ISSUE TITLE
访问localhost:4000显示not found

### ISSUE THREAD

**Issue by PonderK** [tnfe/shida#11]
按照readme开发调试中的步骤运行的，唯一有一些不同的可能是mongodb配置，我安装完之后打开数据库后没做其他配置工作，但分别执行npm run watch-publish和npm run dev-server都没有报错，请问该怎么解决？

**Comment by aliaszz** [comment]
可以提供下 npm run watch-publish 和 npm run dev-server 的执行信息嘛，目前的描述还不足以定位问题。

**Comment by PonderK** [comment]
您好，两个命令都没有报错。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tnfe/shida"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月30日(星期一) 晚上8:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tnfe/shida] 访问localhost:4000显示not found (Issue #11)





 
可以提供下 npm run watch-publish 和 npm run dev-server 的执行信息嘛，目前的描述还不足以定位问题。

**Comment by aliaszz** [comment]
嗯，知道没有报错哈。
可以提供下执行命令后终端内打印出来的信息或者截图嘛。

**Comment by PonderK** [comment]
PS C:\Users\wang\Desktop\shida-main> npm run watch-publish

> ffcreator-lowcode@0.1.0 watch-publish C:\Users\wang\Desktop\shida-main
> npm run watch-build & npm run watch-dist


> ffcreator-lowcode@0.1.0 watch-build C:\Users\wang\Desktop\shida-main
> vue-cli-service build --watch


98% after emitting CopyPlugin

 DONE  Compiled successfully in 21255ms                                                                         18:35:01
  File                      Size                     Gzipped

  dist\static\psd.min.js    414.69 KiB               204.45 KiB
  dist\index.js             12188.87 KiB             2114.56 KiB
  dist\2.js                 1701.70 KiB              178.87 KiB
  dist\4.js                 1309.12 KiB              233.81 KiB
  dist\3.js                 256.29 KiB               32.20 KiB
  dist\0.js                 190.76 KiB               29.11 KiB
  dist\6.js                 123.00 KiB               22.17 KiB
  dist\5.js                 120.18 KiB               17.00 KiB
  dist\1.js                 84.19 KiB                12.36 KiB
  dist\7.js                 73.13 KiB                9.96 KiB
  dist\8.js                 72.35 KiB                9.59 KiB
  dist\9.js                 71.41 KiB                11.14 KiB
  dist\10.js                70.99 KiB                11.00 KiB
  dist\11.js                40.86 KiB                7.51 KiB

  Images and other types of assets omitted.

 DONE  Build complete. Watching for changes...

===================================================================
PS C:\Users\wang\Desktop\shida-main> npm run dev-server

> ffcreator-lowcode@0.1.0 dev-server C:\Users\wang\Desktop\shida-main
> nodemon server/app.js dev -L

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server/app.js dev`
(node:13092) ExperimentalWarning: The fs.promises API is experimental
server is starting........!
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] starting `node server/app.js dev`
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] starting `node server/app.js dev`
[nodemon] restarting due to changes...
[nodemon] starting `node server/app.js dev`
(node:4644) ExperimentalWarning: The fs.promises API is experimental
server is starting........!

================================================
 @另外我有尝试运行[quark-h5](https://github.com/huangwei9527/quark-h5)这个项目，是可以运行起来的。
=====================================================================
环境：Node.js  v10.12.0; mongodb4.4.4

**Comment by PonderK** [comment]
不好意思，刚才用邮件回复您的，详细信息已经附在问题下方了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tnfe/shida"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月30日(星期一) 晚上8:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tnfe/shida] 访问localhost:4000显示not found (Issue #11)





 
嗯，知道没有报错哈。
 可以提供下执行命令后终端内打印出来的信息或者截图嘛。

**Comment by aliaszz** [comment]
publish的输出看起来不全，正常编译后产出应该包含这些文件。
```
server/public
├── 0.js
├── 1.js
├── 10.js
├── 11.js
├── 2.js
├── 3.js
├── 4.js
├── 5.js
├── 6.js
├── 7.js
├── 8.js
├── 9.js
├── favicon.ico
├── index.html
├── index.js
└── static
    ├── demo
    │   ├── demo.jpg
    │   ├── demo.mp3
    │   ├── demo.mp4
    │   ├── music.png
    │   ├── video.jpg
    │   └── wryh.ttf
    ├── fonts
    │   ├── element-icons.535877f5.woff
    │   ├── element-icons.732389de.ttf
    │   ├── iconfont.2adcd9a2.eot
    │   ├── iconfont.4e2258a0.ttf
    │   └── iconfont.687560f7.woff
    ├── img
    │   ├── headerImage.baefd97f.png
    │   ├── iconfont.d177932d.svg
    │   ├── logo.49367023.jpg
    │   ├── nodata.8468dc19.png
    │   ├── pagecover.e918ae3e.jpg
    │   └── use-beb469.beb469b6.png
    └── psd.min.js

4 directories, 33 files
```
可以先结合 ``` Failed to load resource: the server responded with a status of 404 (Not Found) ``` 提示的缺失文件比对一下。

**Comment by PonderK** [comment]
> publish的输出看起来不全，正常编译后产出应该包含这些文件。
> 
> ```
> server/public
> ├── 0.js
> ├── 1.js
> ├── 10.js
> ├── 11.js
> ├── 2.js
> ├── 3.js
> ├── 4.js
> ├── 5.js
> ├── 6.js
> ├── 7.js
> ├── 8.js
> ├── 9.js
> ├── favicon.ico
> ├── index.html
> ├── index.js
> └── static
>     ├── demo
>     │   ├── demo.jpg
>     │   ├── demo.mp3
>     │   ├── demo.mp4
>     │   ├── music.png
>     │   ├── video.jpg
>     │   └── wryh.ttf
>     ├── fonts
>     │   ├── element-icons.535877f5.woff
>     │   ├── element-icons.732389de.ttf
>     │   ├── iconfont.2adcd9a2.eot
>     │   ├── iconfont.4e2258a0.ttf
>     │   └── iconfont.687560f7.woff
>     ├── img
>     │   ├── headerImage.baefd97f.png
>     │   ├── iconfont.d177932d.svg
>     │   ├── logo.49367023.jpg
>     │   ├── nodata.8468dc19.png
>     │   ├── pagecover.e918ae3e.jpg
>     │   └── use-beb469.beb469b6.png
>     └── psd.min.js
> 
> 4 directories, 33 files
> ```
> 
> 可以先结合 `Failed to load resource: the server responded with a status of 404 (Not Found)` 提示的缺失文件比对一下。

好的，我研究一下，感谢回复！

**Comment by PonderK** [comment]
> publish的输出看起来不全，正常编译后产出应该包含这些文件。
> 
> ```
> server/public
> ├── 0.js
> ├── 1.js
> ├── 10.js
> ├── 11.js
> ├── 2.js
> ├── 3.js
> ├── 4.js
> ├── 5.js
> ├── 6.js
> ├── 7.js
> ├── 8.js
> ├── 9.js
> ├── favicon.ico
> ├── index.html
> ├── index.js
> └── static
>     ├── demo
>     │   ├── demo.jpg
>     │   ├── demo.mp3
>     │   ├── demo.mp4
>     │   ├── music.png
>     │   ├── video.jpg
>     │   └── wryh.ttf
>     ├── fonts
>     │   ├── element-icons.535877f5.woff
>     │   ├── element-icons.732389de.ttf
>     │   ├── iconfont.2adcd9a2.eot
>     │   ├── iconfont.4e2258a0.ttf
>     │   └── iconfont.687560f7.woff
>     ├── img
>     │   ├── headerImage.baefd97f.png
>     │   ├── iconfont.d177932d.svg
>     │   ├── logo.49367023.jpg
>     │   ├── nodata.8468dc19.png
>     │   ├── pagecover.e918ae3e.jpg
>     │   └── use-beb469.beb469b6.png
>     └── psd.min.js
> 
> 4 directories, 33 files
> ```
> 
> 可以先结合 `Failed to load resource: the server responded with a status of 404 (Not Found)` 提示的缺失文件比对一下。

再次感谢回复！我暂时这个问题已经解决了，需要把dist文件夹里如上文件，手动复制到server/public文件夹下！
