### ISSUE TITLE
npm i c出现问题

### ISSUE THREAD

**Issue by Evanl-lai** [tnfe/shida#28]
请问作者有时间把node-sass这个毒瘤去掉了吗，太折磨人这个东西

**Comment by drawcall** [comment]
可以提交pr

**Comment by chakson** [comment]
> 请问作者有时间把node-sass这个毒瘤去掉了吗，太折磨人这个东西

哈哈，node-sass确实是毒瘤

**Comment by drawcall** [comment]
Please check the latest code
