### ISSUE TITLE
发布生成视频无法合成视频

### ISSUE THREAD

**Issue by xianzifeng** [tnfe/shida#4]
在本地部署之后，点击发布按钮，无法进行合同视频，
![图片](https://user-images.githubusercontent.com/7110599/153835291-3d64fd7a-1782-4077-b989-a6a1edaee970.png)
![图片](https://user-images.githubusercontent.com/7110599/153835324-dcc4898f-5049-48c6-8627-149deff9b252.png)
后台提示， 未找到ffmpeg,   我本地已经安装ffmpeg , 请教要如何操作

**Comment by drawcall** [comment]
Note: Please set FFmpeg as a global variable, otherwise you need to use setFFmpegPath to add FFmpeg native path
